import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import './globals.scss';
import './root.scss';
import LayoutRoot from '@/app/layout.c';

// const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: 'Iskender',
	description: 'Generated by Moore Studio'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<LayoutRoot>{children}</LayoutRoot>
			</body>
		</html>
	);
}
